name: Axon Bill Of Materials

on:
  push:
    branches:
      - main
      - master
      - axon-bom-*.*.x

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    continue-on-error: true # do not fail the whole job if one of the steps fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 8
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build
        run: |
          ./mvnw -B -U -Dstyle.color=always verify -DskipTests=true

      - name: Deploy to Sonatype
        if: success()
        run: |
          mvn -B -U -Dstyle.color=always deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_TOKEN_ID }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASS }}

      - name: Notify success to Slack
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel_id: CAGSEC92A
          status: SUCCESS
          color: good

      - name: Notify failure to Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel_id: CAGSEC92A
          status: FAILED
          color: danger
