name: Axon Bill Of Materials

on:
  pull_request:

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'zulu'
          java-version: 8
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build
        run: |
          ./mvnw -B -U verify -DskipTests=true
